apiVersion: v1
kind: Service
metadata:
  labels:
    test.service: test-server
  name: app-server
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    test.service: test-server
status:
  loadBalancer: {}
