apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    test.service: test-server
  name: app-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        test.service: test-server
    spec:
      containers:
        image: richab123/app_server:0.0.1
        name: test-server
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
