apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    test.service: test-server
  name: hello-kubernetes-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      test.service: test-server
  template:
    metadata:
      labels:
        test.service: test-server
    spec:
      containers:
      - name: hello-kubernetes
        image: nishantchauhan/app-server
        ports:
        - containerPort: 8080
      restartPolicy: Always
status: {}
